stages: 
  - prepare
  - release

prepare:release:
  stage: prepare
  rules:
    - if: '$CI_COMMIT_TAG =~ /.*7.0.*/'
      when: always
    - if: '$CI_COMMIT_TAG =~ /.*6.0.*/'
      when: always
    - when: never
  before_script:
    - echo "setting build environment"
    - sudo apk update
    - sudo apk upgrade
    - sudo apk add dotnet7-sdk xz gzip
  script:
    - export _cli_root=/usr/lib/dotnet
    - echo "running release_job for $TAG"
    - _InitializeDotNetCli="$_cli_root" DOTNET_INSTALL_DIR="$_cli_root" DotNetBuildFromSource=true ./build.sh /p:ArcadeBuildTarball=true /p:EnableSourceLink=false
    - gzip -cd artifacts/packages/*/*/dotnet-*.tar.gz | xz -T0 -9 -vv -c > dotnet-$CI_COMMIT_TAG.tar.xz
  after_script:
    - echo "JOB_ID=$CI_JOB_ID" > job.env
  artifacts:
    paths:
      - dotnet-$CI_COMMIT_TAG.tar.xz
    expire_in: never
    reports:
      dotenv: job.env


create:release:
  stage: release
  needs:
    - job: prepare:release
      artifacts: true
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "Create Release $GI_COMMIT_TAG"
    - echo $JOB_ID
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_SHA'
    assets:
      links:
        - name: "Tarball (tar.xz)"
          filepath: "/tarball/dotnet-$CI_COMMIT_TAG.tar.xz"
          url: "https://lab.ilot.io/dotnet/installer/-/jobs/$JOB_ID/artifacts/raw/dotnet-$CI_COMMIT_TAG.tar.xz"
