stages: 
  - release

release_job:
  stage: release
  script:
    - export EXTRA_DESCRIPTION="some message"
    - export TAG="$(git describe --tag)"
    - echo "setting build environment"
    - sudo apk update
    - sudo apk upgrade
    - sudo apk add dotnet7-sdk
    - export _cli_root=/usr/lib/dotnet
    - echo "running release_job for $TAG"
    - _InitializeDotNetCli="$_cli_root" DOTNET_INSTALL_DIR="$_cli_root" DotNetBuildFromSource=true ./build.sh /p:ArcadeBuildTarball=true
  artifacts:
    paths:
      - artifacts/packages/
  release:
    name: 'Release $TAG'
    description: 'Created using the release-cli $EXTRA_DESCRIPTION'  # $EXTRA_DESCRIPTION and the $TAG
    tag_name: '$TAG'                                                 # variables must be defined elsewhere
    ref: '$CI_COMMIT_SHA'                                            # in the pipeline. For example, in the
